version: '3.8'
services:
  redis: # Name of container
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
    networks:
      - websmart
  dev_db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data   
    networks:
      - websmart
volumes:
  db_data: 
  redis:
    driver: local   

networks:
  websmart: