version: "3.8"
services: 
  nest_api:  
    image: nest_api
    restart: always
    build:
     dockerfile: Dockerfile
     context: .
     target: development
    ports:
      - 4444:4444
    command: npm run start:migrate:dev
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
     - websmart  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
     - websmart  
    ports:
      - "8080:80"     